Replicating the confusing issue I ran into when I tried to name the module the same as the Trait.  The messages I got
  error[E0599]: no function or associated item named `new` found for struct `Boolish::TwoBitCounter` in the current scope
     --> src/main.rs:179:39
      |
  37  |     pub struct TwoBitCounter {
      |     ------------------------ function or associated item `new` not found for this
  ...
  179 |         let pht = vec![TwoBitCounter::new(true); 1 << addr_bits];
      |                                       ^^^ function or associated item not found in `Boolish::TwoBitCounter`
      |
      = help: items from traits can only be used if the trait is in scope
  help: the following trait is implemented but not in scope; perhaps add a `use` for it:
      |
  2   | use crate::Boolish::Boolish;
      |

really didn't catch the real issue at all and had me tearing out my
hair trying to understand why visibility was suddendly changed by
moving things to a module.